# Preprocessing code to turn the WALS data into a more usable format.
# This is run pre-build; what is distributed with the R package is
# the RData objects generated by this code.


# Dependencies
require(stringr)


# Paths

rawfolder <- "data-raw/wals_dataset.cldf"
langfolder <- "data-raw/wals_language.csv"
samplefolder <- "data-raw/samples"


# Function definitions

make_WALS_languages <- function(folder = langfolder,
                                samfolder = samplefolder) {
  langs <- read.csv(paste0(folder, "/language.csv"),
                    fileEncoding="UTF-8",
                    colClasses="character")
  langs <- langs[, c("wals_code",
                     "iso_code",
                     "glottocode",
                     "Name",
                     "latitude",
                     "longitude",
                     "genus",
                     "family",
                     "macroarea",
                     "countrycodes")]
  names(langs) <- c("language_ID",
                    "iso_code",
                    "glottocode",
                    "language",
                    "latitude",
                    "longitude",
                    "genus",
                    "family",
                    "macroarea",
                    "countrycodes")
  sample100 <- read.csv(paste0(samfolder, "/wals_100_sample.csv"), fileEncoding="UTF-8")$language_ID
  sample200 <- read.csv(paste0(samfolder, "/wals_200_sample.csv"), fileEncoding="UTF-8")$language_ID
  langs$in_WALS_100 <- ifelse(langs$language_ID %in% sample100, yes=TRUE, no=FALSE)
  langs$in_WALS_200 <- ifelse(langs$language_ID %in% sample200, yes=TRUE, no=FALSE)
  langs <- langs[, c("language_ID", "iso_code", "glottocode", "language", "family", "genus", "macroarea", "countrycodes", "latitude", "longitude", "in_WALS_100", "in_WALS_200")]
  langs$latitude <- as.numeric(langs$latitude)
  langs$longitude <- as.numeric(langs$longitude)

  cols <- names(langs)
  for (col in cols) {
    if (!(col %in% c("latitude", "longitude", "in_WALS_100", "in_WALS_200"))) {
    langs[[col]] <- factor(langs[[col]])
    Encoding(levels(langs[[col]])) <- "UTF-8"
    }
  }

  langs
}


make_WALS_features <- function(folder = rawfolder) {
  feats <- read.csv(paste0(folder, "/parameters.csv"),
                    fileEncoding="UTF-8",
                    colClasses="character")
  feats <- feats[, c("ID", "Name")]
  names(feats) <- c("ID", "feature")
  codes <- read.csv(paste0(folder, "/codes.csv"),
                    fileEncoding="UTF-8")
  codes <- codes[, c("ID", "Parameter_ID", "Name", "Number")]
  names(codes) <- c("code_ID", "ID", "value", "value_ID")
  feats <- merge(feats, codes, by="ID")
  feats <- feats[!duplicated(feats), ]
  names(feats)[1] <- "feature_ID"
  feats <- feats[, c("feature_ID", "feature", "value_ID", "value", "code_ID")]

  #feats$value_ID <- as.numeric(feats$value_ID)

  cols <- names(feats)
  for (col in cols) {
    #if (!(col %in% c("value_ID"))) {
    feats[[col]] <- factor(feats[[col]])
    Encoding(levels(feats[[col]])) <- "UTF-8"
    #}
  }

  feats
}


make_WALS_contributions <- function(folder = rawfolder) {
  conts <- read.csv(paste0(folder, "/contributions.csv"),
                    fileEncoding="UTF-8",
                    colClasses="character")
  conts <- conts[, c("ID", "Contributors")]
  names(conts) <- c("contribution_ID", "contributors")
  conts$contribution_ID <- factor(conts$contribution_ID)
  conts$contributors <- factor(conts$contributors)
  Encoding(levels(conts$contribution_ID)) <- "UTF-8"
  Encoding(levels(conts$contributors)) <- "UTF-8"
  conts
}


make_WALS <- function(folder = rawfolder) {
  wals <- read.csv(paste0(folder, "/values.csv"),
                   fileEncoding="UTF-8",
                   colClasses="character")
  names(wals) <- c("combined_ID",
                   "language_ID",
                   "feature_ID",
                   "value",
                   "code_ID",
                   "comment",
                   "source",
                   "contribution_ID")
  wals <- wals[, -c(3,4)]
  langs <- make_WALS_languages()
  feats <- make_WALS_features()
  conts <- make_WALS_contributions()
  wals <- merge(wals, langs, by="language_ID")
  wals <- merge(wals, feats, by="code_ID")
  wals <- merge(wals, conts, by="contribution_ID")

  wals <- wals[!duplicated(wals), ]
  wals <- wals[, c("combined_ID",
                   "feature_ID",
                   "feature",
                   "value_ID",
                   "value",
                   "code_ID",
                   "language_ID",
                   "iso_code",
                   "glottocode",
                   "language",
                   "family",
                   "genus",
                   "macroarea",
                   "countrycodes",
                   "latitude",
                   "longitude",
                   "in_WALS_100",
                   "in_WALS_200",
                   "source",
                   "contributors")]
  #wals$value <- defactorize(wals$value)

  cols <- names(wals)
  for (col in cols) {
    #if (!(col %in% c("value_ID", "latitude", "longitude", "in_WALS_100", "in_WALS_200"))) {
    if (!(col %in% c("latitude", "longitude", "in_WALS_100", "in_WALS_200"))) {
    wals[[col]] <- factor(wals[[col]])
    Encoding(levels(wals[[col]])) <- "UTF-8"
    }
  }

  wals
}


defactorize <- function(x) {
  levels(x)[as.numeric(x)]
}



# Prepare WALS

compress <- "xz"

WALS_languages <- make_WALS_languages()
save(WALS_languages, file="data/WALS_languages.RData", compress=compress)

WALS_features <- make_WALS_features()
save(WALS_features, file="data/WALS_features.RData", compress=compress)

WALS <- make_WALS()
save(WALS, file="data/WALS.RData", compress=compress)

rm(WALS_languages)
rm(WALS_features)
rm(WALS)
