# Preprocessing code to turn the WALS data into a more usable format.
# This is run pre-build; what is distributed with the R package is
# the RData objects generated by this code.


# Dependencies
require(stringr)


# Paths

rawfolder <- "data-raw/wals_dataset.cldf"
langfolder <- "data-raw/wals_language.csv"
samplefolder <- "data-raw/samples"


# Function definitions

make_WALS <- function(folder = rawfolder) {
  feats <- make_WALS_features()
  feats <- feats[, c("feature_ID", "feature")]
  langs <- make_WALS_languages()
  conts <- make_WALS_contributions()
  hWALS <- read.csv(paste0(folder, "/values.csv"), colClasses="character")
  names(hWALS) <- c("combined_ID", "language_ID", "feature_ID", "value", "code_ID", "comment", "source", "contribution_ID")
  hWALS <- merge(hWALS, feats, by="feature_ID")
  hWALS <- merge(hWALS, langs, by="language_ID")
  hWALS <- merge(x=hWALS, y=conts, by="contribution_ID")
  hWALS$value_ID <- str_replace(hWALS$code_ID, pattern="^[^-]*-", replacement="")
  hWALS$value_ID <- as.numeric(hWALS$value_ID)
  hWALS <- hWALS[, c("combined_ID", "language_ID", "feature_ID", "value_ID", "code_ID", "language", "feature", "value", "iso_code", "glottocode", "latitude", "longitude", "genus", "family", "macroarea", "countrycodes", "in_WALS_100_sample", "in_WALS_200_sample", "source", "contributors")]
  hWALS <- hWALS[!duplicated(hWALS), ]
  hWALS
}

make_WALS_contributions <- function(folder = rawfolder) {
  hWALS_contributions <- read.csv(paste0(folder, "/contributions.csv"), colClasses="character")
  names(hWALS_contributions) <- c("contribution_ID", "name", "description", "contributors")
  hWALS_contributions <- hWALS_contributions[, c("contribution_ID", "contributors")]
  hWALS_contributions
}

make_WALS_languages <- function(folder = langfolder,
                                samfolder = samplefolder) {
  hWALS_languages <- read.csv(paste0(folder, "/language.csv"), colClasses="character")
  hWALS_languages <- hWALS_languages[, c("wals_code", "iso_code", "glottocode", "Name", "latitude", "longitude", "genus", "family", "macroarea", "countrycodes")]
  names(hWALS_languages) <- c("language_ID", "iso_code", "glottocode", "language", "latitude", "longitude", "genus", "family", "macroarea", "countrycodes")
  hWALS_languages$latitude <- as.numeric(hWALS_languages$latitude)
  hWALS_languages$longitude <- as.numeric(hWALS_languages$longitude)
  sample100 <- read.csv(paste0(samfolder, "/wals_100_sample.csv"), colClasses="character")$language_ID
  sample200 <- read.csv(paste0(samfolder, "/wals_200_sample.csv"), colClasses="character")$language_ID
  hWALS_languages$in_WALS_100_sample <- ifelse(hWALS_languages$language_ID %in% sample100, yes=TRUE, no=FALSE)
  hWALS_languages$in_WALS_200_sample <- ifelse(hWALS_languages$language_ID %in% sample200, yes=TRUE, no=FALSE)
  hWALS_languages
}

make_WALS_features <- function(folder = rawfolder) {
  hWALS_parameters <- read.csv(paste0(folder, "/parameters.csv"), colClasses="character")
  hWALS_parameters <- hWALS_parameters[, c("ID", "Name")]
  hWALS_codes <- read.csv(paste0(folder, "/codes.csv"), colClasses="character")
  hWALS_features <- NULL
  for (feat in unique(sort(hWALS_parameters$ID))) {
    df <- hWALS_codes[hWALS_codes$Parameter_ID == feat, ]
    df <- df[, c("Parameter_ID", "Name", "Number")]
    names(df) <- c("ID", "value_description", "value")
    df$name <- hWALS_parameters[hWALS_parameters$ID == feat, ]$Name
    df <- data.frame(feature=df$ID, feature_description=df$name, value=df$value, value_description=df$value_description)
    hWALS_features <- rbind(hWALS_features, df)
  }
  for (i in 1:ncol(hWALS_features)) {
    hWALS_features[,i] <- defactorize(hWALS_features[,i])
  }
  names(hWALS_features) <- c("feature_ID", "feature", "value_ID", "value")
  hWALS_features
}

defactorize <- function(x) {
  levels(x)[as.numeric(x)]
}

mysave <- function(x) {
  save(x, file=paste0("data/", deparse(substitute(x)), ".RData"))
}


# Prepare WALS

WALS_contributions <- make_WALS_contributions()
save(WALS_contributions, file="data/WALS_contributions.RData")
rm(WALS_contributions)

WALS_languages <- make_WALS_languages()
save(WALS_languages, file="data/WALS_languages.RData")
rm(WALS_languages)

WALS_features <- make_WALS_features()
save(WALS_features, file="data/WALS_features.RData")
rm(WALS_features)

WALS <- make_WALS()
save(WALS, file="data/WALS.RData")
rm(WALS)

WALS_nometa <- WALS[, c("language_ID", "feature_ID", "value_ID", "latitude", "longitude")]
save(WALS_nometa, file="data/WALS_nometa.RData")
rm(WALS_nometa)

WALS_100 <- WALS[WALS$in_WALS_100_sample, ]
save(WALS_100, file="data/WALS_100.RData")
rm(WALS_100)

WALS_200 <- WALS[WALS$in_WALS_200_sample, ]
save(WALS_200, file="data/WALS_200.RData")
rm(WALS_200)
